#ifndef MACHINE_CREATE_H
#define MACHINE_CREATE_H

#include "libultra/ultra64.h"

typedef enum WorksMachineMode {
    /* 00 */ MACHINE_MODE_0,
    /* 01 */ MACHINE_MODE_MENU,
    /* 02 */ MACHINE_MODE_MENU_COLOR,
    /* 03 */ MACHINE_MODE_LOAD_GET_FILE,
    /* 04 */ MACHINE_MODE_LOAD_SELECT_FILE,
    /* 05 */ MACHINE_MODE_LOAD_SELECT_SUPER,
    /* 06 */ MACHINE_MODE_LOAD_CONFIRM,
    /* 07 */ MACHINE_MODE_LOAD_NOW,
    /* 08 */ MACHINE_MODE_SAVE_FILE_EXIST_BEFORE,
    /* 09 */ MACHINE_MODE_SAVE_FILE_EXIST,
    /* 10 */ MACHINE_MODE_SAVE_GET_FILE,
    /* 11 */ MACHINE_MODE_OVERWRITE_CONFIRM,
    /* 12 */ MACHINE_MODE_OVERWRITE_FILE_EXIST,
    /* 13 */ MACHINE_MODE_OVERWRITE_GET_FILE,
    /* 14 */ MACHINE_MODE_DELETE_GET_FILE,
    /* 15 */ MACHINE_MODE_DELETE_SELECT_FILE,
    /* 16 */ MACHINE_MODE_DELETE_CONFIRM,
    /* 17 */ MACHINE_MODE_PARTS,
    /* 18 */ MACHINE_MODE_SELECT_LINE,
    /* 19 */ MACHINE_MODE_SELECT_MARK,
    /* 20 */ MACHINE_MODE_BODY_COLOR,
    /* 21 */ MACHINE_MODE_LINE_COLOR,
    /* 22 */ MACHINE_MODE_NUMBER_COLOR,
    /* 23 */ MACHINE_MODE_COCKPIT_COLOR,
    /* 24 */ MACHINE_MODE_ENTRY_GET_FILE,
    /* 25 */ MACHINE_MODE_ENTRY_SELECT_FILE,
    /* 26 */ MACHINE_MODE_ENTRY_SELECT_SUPER,
    /* 27 */ MACHINE_MODE_ENTRY_LOAD_NOW,
    /* 28 */ MACHINE_MODE_ENTRY, // Machine Select
    /* 29 */ MACHINE_MODE_ENTRY_ALLCLEAR_CONFIRM,
    /* 30 */ MACHINE_MODE_ENTRY_CLEAR_SELECT_FILE,
    /* 31 */ MACHINE_MODE_ENTRY_CLEAR_SELECT_SUPER,
    /* 32 */ MACHINE_MODE_ENTRY_CLEAR_CONFIRM,
    /* 33 */ MACHINE_MODE_ENTRY_CLEAR_SUPER_CONFIRM,
    /* 34 */ MACHINE_MODE_MNAME,
    /* 35 */ MACHINE_MODE_SETTING,
    /* 36 */ MACHINE_MODE_MESSAGE_BUTTON,
    /* 37 */ MACHINE_MODE_CHECKSUM_ERROR,
} WorksMachineMode;

typedef enum MachineStatSelectionState {
    MACHINE_STAT_INVALID,
    MACHINE_STAT_AVAILABLE,
    MACHINE_STAT_SELECTED,
} MachineStatSelectionState;

typedef enum MachineStatValue {
    MACHINE_STAT_E,
    MACHINE_STAT_D,
    MACHINE_STAT_C,
    MACHINE_STAT_B,
    MACHINE_STAT_A,
} MachineStatValue;

#define MACHINE_STAT_MAX_WEIGHTING 13

extern s32 gWorksMachineMode;

#endif // MACHINE_CREATE_H
