#include "audio.h"
#include "macros.h"

s8 audioPad80025C00[0x10];
SynthesisReverb gSynthReverbs[1];
s8 audioPad80025D40[0x10];
u16 D_80025D50;
s8 gUseReverb;
s8 gNumSynthReverbs;
u16 D_80025D54;
s8 audioPad80025D58[0x8];
void* gCurLoadedBook;
NoteSubEu* gNoteSubsEu;
AudioAllocPool gSessionPool;
AudioAllocPool gExternalPool;
AudioAllocPool gInitPool;
AudioAllocPool gMiscPool;
s8 audioPad80025DA8[0x20];
AudioAllocPool gCachePool;
AudioAllocPool gPersistentCommonPool;
AudioAllocPool gTemporaryCommonPool;
AudioCache gSeqCache;
AudioCache gFontCache;
AudioCache gSampleBankCache;
AudioPermanentCache gPermanentCache;
AudioSampleCache gPersistentSampleCache;
AudioSampleCache gTemporarySampleCache;
AudioSessionPoolSplit gSessionPoolSplit;
AudioCachePoolSplit gCachePoolSplit;
AudioCommonPoolSplit gPersistentCommonPoolSplit;
AudioCommonPoolSplit gTemporaryCommonPoolSplit;
u8 gSampleFontLoadStatus[0x30];
u8 gFontLoadStatus[0x30];
u8 gSeqLoadStatus[0x30];
volatile u8 gResetStatus;
u8 gSpecId;
s32 gResetFadeoutFramesLeft;
f32* gAdsrDecayTable;
Note* gNotes;
SequencePlayer gSeqPlayers[3];
SequenceLayer gSeqLayers[64];
SequenceChannel gSeqChannelNone;
AudioListItem gLayerFreeList;
NotePool gNoteFreeLists;
Sample* gUsedSamples[128];
AudioPreloadReq gPreloadSampleStack[128];
s32 gNumUsedSamples;
s32 gPreloadSampleStackTop;
AudioAsyncLoad gAsyncLoads[16];
OSMesgQueue gExternalLoadQueue;
OSMesg gExternalLoadMsgBuf[8];
OSMesgQueue gPreloadSampleQueue;
OSMesg gPreloadSampleMsgBuf[8];
OSMesgQueue gCurAudioFrameDmaQueue;
OSMesg gCurAudioFrameDmaMsgBuf[64];
OSIoMesg gCurAudioFrameDmaIoMsgBuf[64];
OSMesgQueue gSyncDmaQueue;
OSMesg gSyncDmaMsg;
OSIoMesg gSyncDmaIoMsg;
SampleDma* gSampleDmas;
u32 gSampleDmaCount;
u32 gSampleDmaListSize1;
u32 gSampleDmaListSize2;
u8 gSampleDmaReuseQueue1[0x100];
u8 gSampleDmaReuseQueue2[0x100];
u8 gSampleDmaReuseQueue1RdPos;
u8 gSampleDmaReuseQueue2RdPos;
u8 gSampleDmaReuseQueue1WrPos;
u8 gSampleDmaReuseQueue2WrPos;
AudioTable* gSequenceTable;
AudioTable* gSoundFontTable;
AudioTable* gSampleBankTable;
u8* gSeqFontTable;
u16 gNumSequences;
SoundFont* gSoundFontList;
AudioBufferParameters gAudioBufferParams;
size_t gSampleDmaBufSize;
s32 gMaxAudioCmds;
s32 gNumNotes;
s16 gMaxTempo;
s8 gSoundMode;
volatile s32 gTotalTaskCount;
s32 gCurAudioFrameDmaCount;
s32 gRspTaskIndex;
s32 gCurAiBufIndex;
Acmd* gAbiCmdBuffs[2];
Acmd* gCurAbiCmdBuffer;
AudioTask* gCurTask;
AudioTask gRspTask[2];
f32 gMaxTempoTvTypeFactors;
s32 gRefreshRate;
s16* gAiBuffers[3];
s16 gAiBufLengths[3];
u32 gAudioRandom;
s8 audioPad8002AB38[0x4];
volatile u32 gResetTimer;
AudioCmd gThreadCmdBuffer[256];
u16 gThreadCmdChannelMask[3];
u8 gThreadCmdWritePos;
u8 gThreadCmdReadPos;
u8 gThreadCmdQueueFinished;
OSMesg gAudioTaskStartMsg[1];
OSMesgQueue gAudioTaskStartQueue;
OSMesgQueue* gAudioTaskStartQueuePtr;
OSMesg gThreadCmdProcMsg[4];
OSMesgQueue gThreadCmdProcQueue;
OSMesgQueue* gThreadCmdProcQueuePtr;
OSMesg gAudioResetMsg[1];
OSMesgQueue gAudioResetQueue;
OSMesgQueue* gAudioResetQueuePtr;

ReverbSettings D_800D1C20[] = {
    { 1, 0x20, 0x7000, 0x7FFF, 0, 0, 255 },
};

AudioSpec gAudioSpecs[] = {
    { 32000, 1, 10, 2, ARRAY_COUNT(D_800D1C20), D_800D1C20, 0x7FFF, 0, 0, 0, 0, 0, 0, 0x22C00, 0 },
};

s8 D_800D1C64 = 10;
s16 gSeqTicksPerBeat = 0x30;
s32 gAudioHeapSize = sizeof(gAudioHeap);
size_t gInitPoolSize = 0x6C00;
size_t gPermanentPoolSize = 0x3C00;
