#ifndef COURSE_EDIT_H
#define COURSE_EDIT_H

typedef enum CourseEditState {
    COURSE_EDIT_STATE_0,
    COURSE_EDIT_STATE_1,
    COURSE_EDIT_NAME_ENTRY,
    COURSE_EDIT_STATE_3,
    COURSE_EDIT_OPTIONS_MENU,
    COURSE_EDIT_SELECTION_BOX,
    COURSE_EDIT_STATE_6,
    COURSE_EDIT_STATE_7,
    COURSE_EDIT_STATE_8,
    COURSE_EDIT_STATE_9,
    COURSE_EDIT_STATE_10,
    COURSE_EDIT_STATE_11,
    COURSE_EDIT_STATE_12,
    COURSE_EDIT_STATE_13,
    COURSE_EDIT_STATE_14,
    COURSE_EDIT_STATE_15,
    COURSE_EDIT_STATE_16,
    COURSE_EDIT_STATE_17,
    COURSE_EDIT_STATE_18,
    COURSE_EDIT_STATE_19,
    COURSE_EDIT_STATE_20,
} CourseEditState;

typedef enum CourseEditOptionMenuState {
    COURSE_EDIT_OPTIONS_MAIN_MENU,
    COURSE_EDIT_OPTIONS_HELP_MENU,
    COURSE_EDIT_OPTIONS_SHOW_HELP_SCREEN,
    COURSE_EDIT_OPTIONS_SHOW_POINT_SELECT_HELP,
    COURSE_EDIT_OPTIONS_CURSOR_SPEED_MENU,
} CourseEditOptionMenuState;

#endif // COURSE_EDIT_H
