#ifndef COURSE_EDIT_H
#define COURSE_EDIT_H

typedef enum CourseEditState {
    COURSE_EDIT_STATE_0,
    COURSE_EDIT_IN_MENU,
    COURSE_EDIT_NAME_ENTRY,
    COURSE_EDIT_IN_FILE_MENU,
    COURSE_EDIT_OPTIONS_MENU,
    COURSE_EDIT_SELECTION_BOX,
    COURSE_EDIT_STATE_6,
    COURSE_EDIT_REGISTER_FILE_MENU = 32,
    COURSE_EDIT_STATE_49 = 49,
    COURSE_EDIT_STATE_50,
    COURSE_EDIT_VALIDATE_FILE_NAMES = 54,
} CourseEditState;

typedef enum CourseEditOptionMenuState {
    COURSE_EDIT_OPTIONS_MAIN_MENU,
    COURSE_EDIT_OPTIONS_HELP_MENU,
    COURSE_EDIT_OPTIONS_SHOW_HELP_SCREEN,
    COURSE_EDIT_OPTIONS_SHOW_POINT_SELECT_HELP,
    COURSE_EDIT_OPTIONS_CURSOR_SPEED_MENU,
} CourseEditOptionMenuState;

#endif // COURSE_EDIT_H
