#ifndef FUNCTIONS_H
#define FUNCTIONS_H

#include "sys.h"
#include "controller.h"
#include "fzx_math.h"
#include "fzx_object.h"
#include "unk_structs.h"
#include "PR/leo.h"

void Game_ThreadEntry(void* arg0);
void Audio_ThreadEntry(void* arg0);

void Game_Init(void);
Gfx* func_80069698(Gfx*);
void Controller_Reset(void);
void Controller_UpdateInputs(void);
void Controller_Init(void);

Gfx* func_8006A00C(Gfx* gfx, s32 scissorBoxType);
void Math_SinTableInit(void);
void Math_Rand1Init(s32 seed, s32 mask);
void Math_Rand2Init(s32 seed, s32 mask);
u32 Math_Rand1(void);
u32 Math_Rand2(void);
s32 Math_Round(f32 num);
s32 Math_OrthonormalizeAroundForward(Mtx3F* basis);
s32 Math_OrthonormalizeAroundUp(Mtx3F* basis);
void func_8006ADE4(s32 arg0, s32 arg1, s32 arg2, s32* red, s32* green, s32* blue);
void Lights_SetSource(Lights1* light, s32 ambientR, s32 ambientG, s32 ambientB, s32 r, s32 g, s32 b, s32 x, s32 y, s32 z);
void Light_SetLookAtSource(LookAt* lookAt, MtxF* mtx);
void Matrix_ToMtx(MtxF* src, Mtx* dest2);
void Matrix_SetLockedLookAt(Mtx* mtx, MtxF* mtxF, f32 scaleZ, f32 scaleY, f32 scaleX, f32 lookAtX, f32 lookAtY, f32 lookAtZ, f32 upX, f32 upY, f32 upZ, f32 xPos, f32 yPos, f32 zPos);
void Matrix_SetLockedLookAtFromVectors(Mtx* mtx, MtxF* mtxF, f32 scaleZ, f32 scaleY, f32 scaleX, Vec3f* lookAt, Vec3f* up, Vec3f* pos);
void Matrix_ScaleFrom3DMatrix(Mtx* mtx, MtxF* mtxF, f32 xScale, f32 yScale, f32 zScale, Mtx3F* matrix3D, Vec3f* pos);
void Matrix_SetTransRot(Mtx* mtx, MtxF* mtxF, f32 arg2, s32 xRot, s32 yRot, s32 zRot, f32 xPos, f32 yPos, f32 zPos);
void Matrix_SetAxisRotation(Mtx* arg0, MtxF* arg1, f32 arg2, s32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, f32 arg8, f32 arg9);
void Matrix_SetLookAt(Mtx* mtx, MtxF* mtxF, f32 eyeX, f32 eyeY, f32 eyeZ, f32 atX, f32 atY, f32 atZ, f32 upX, f32 upY, f32 upZ);
void Matrix_SetFrustrum(Mtx* mtx, MtxF* mtxF, f32 fovAngle, f32 near, f32 far, f32 fovScaleX, f32 frustumCenterX, f32 fovScaleY, f32 frustumCenterY, u16* perspectiveScale);
void Matrix_SetOrtho(Mtx* mtx, MtxF* mtxF, f32 scale, f32 left, f32 right, f32 top, f32 bottom, f32 near, f32 far);

void func_8006D414(void);
void Course_LandminesViewInteractDataInit(void);
Gfx* Course_GadgetsDraw(Gfx* gfx, s32 arg1);
void Course_JumpsViewInteractDataInit(void);
void Course_DecorationsViewInteractDataInit(void);
void Course_EffectsViewInteractDataInit(s32);

f32 Math_VectorGetDistance(Vec3f arg0, Vec3f arg1);

void Course_SegmentsInit(void);
void Dma_ClearRomCopy(void* romAddr, void* ramAddr, size_t size);
void Dma_RomCopyAsync(void* romAddr, void* ramAddr, size_t size);
void Dma_LoadAssetsAsync(u8* romAddr, u8* ramAddr, size_t size);
void Course_Load(s32 courseIndex);
void Course_GadgetsInit(s32 courseIndex);
void func_800742D0(void);
void func_800742FC(void);
void func_80074428(s32 courseIndex);
void func_80074634(CourseInfo* courseInfo);
void func_800747EC(s32 venue);
void Math_NormalizeXZ(f32* x, f32* z);
void func_80074CE4(CourseInfo*);
void func_80074844(void);

void func_8007515C(void);

void SLForceWritebackDCacheAll(void);
void func_800751FC(char* gameCode);
void func_80075230(OSThread* arg0);
s32 SLLeoReadDiskID_for_start(void);
s32 func_800758F8(void);
s32 SLLeoReadWrite(LEOCmd* cmdBlock, s32 direction, s32 lba, void* vAddr, u32 nLbas, OSMesgQueue* mq);
s32 func_800760F8(void);
s32 func_800761D4(void);
void func_800762B0(LEODiskID diskId);
s32 SLLeoCreateManager(void);
void SLLeoResetClear(void);
void func_8007647C(void);

void Dma_LoadAssets(u8* romAddr, u8* ramAddr, size_t size);
void Dma_LoadOverlay(u8* romAddr, u8* ramAddr, size_t size, void* bssAddr, size_t bssSize);
void Arena_StartInit(void);
void Arena_DefaultStartInit(void);
void Arena_EndInit(void);
void* Arena_Allocate(s32 allocationType, size_t size);
s32 Segment_SetAddress(s32 segment, s32 addr);
s32 Segment_GetAddress(s32 segment);
s32 Segment_SegmentedToVirtual(uintptr_t segmentedAddr);
Gfx* Segment_SetTableAddresses(Gfx*);
void Segment_LoadOverlays(void);
void Segment_LoadAssets(void);

void func_80077CF0(s32 segAddr, size_t size, u8* startAddr);
u8* func_80077D50(unk_80077D50* arg0, s32 arg1);
void* func_80078104(void* arg0, s32 textureSize, s32 arg2, s32 arg3, bool arg4);
TexturePtr func_800783AC(void* arg0);
Gfx* func_80078EA0(Gfx* gfx, unk_80077D50* arg1, s32 left, s32 top, u32 arg4, s32 arg5, s32 arg6, f32 arg7, f32 arg8);
Gfx* func_80078F80(Gfx* gfx, unk_800E3F28* arg1, s32 left, s32 top, u32 arg4, s32 arg5, s32 arg6, f32 arg7, f32 arg8);
void func_800790D4(void);
s32 func_800792D8(unk_800792D8* arg0);
void func_800793E8(s32 arg0, s32 arg1, unk_800792D8* arg2);
void Object_Init(s32 cmdId, s32 left, s32 top, s8 priority);
Gfx* Object_UpdateAndDrawAll(Gfx* gfx);
Object* Object_Get(s32 cmdId);
void func_80079EC8(void);
void func_80079F1C(void);
void Object_LerpPosXToTarget(Object* object, s32 target, s32 stepScale);
void Object_LerpPosYToTarget(Object* object, s32 target);
void Object_LerpPosXToClampedTargetMaxStep(Object* object, s32 target, s32 maxStep);
void Object_LerpPosYToClampedTarget(Object* object, s32 target);
void Object_LerpAwayFromPosX(Object* object, s32 origin, s32 initialStep);

Gfx* func_8007A440(Gfx* gfx, s32 left, s32 top, s32 right, s32 bottom, s32 red, s32 green, s32 blue, s32 alpha);
void func_8007A59C(u16* pixel, s32 size);
void func_8007A828(u16* pixel, size_t size, s32 arg2, s32 arg3, s32 arg4);
Gfx* func_8007AB88(Gfx*);
Gfx* func_8007ABA4(Gfx*);
Gfx* func_8007AD44(Gfx* gfx, u16 red, u16 green, u16 blue, s32 left, s32 top, s32 right, s32 bottom);
Gfx* func_8007AE70(Gfx*);
Gfx* func_8007AC48(Gfx* gfx, u16 red, u16 green, u16 blue);
Gfx* func_8007AE8C(Gfx* gfx, s32 left, s32 top, s32 right, s32 bottom, s32 red, s32 green, s32 blue, s32 alpha);
Gfx* func_8007AF40(Gfx* gfx, s32 left, s32 top, s32 right, s32 bottom, s32 red, s32 green, s32 blue, s32 alpha);
Gfx* func_8007B14C(Gfx* gfx, TexturePtr texture, s32 left, s32 top, s32 width, u32 height, s32 format, s32 size, s32 arg8,
                   s32 arg9, s32 argA, s32 argB);
Gfx* func_8007CDB0(Gfx* gfx, TexturePtr texture, s32 left, s32 top, s32 width, u32 height, f32 arg6, f32 arg7,
                   s32 format, s32 size, s32 argA, s32 argB, s32 argC);
void Controller_SetGlobalInputs(Controller* controller);
Gfx* func_8007DB28(Gfx* gfx, s32 arg1);
void func_8007DEF0(void);
s32 func_8007E008(void);
void func_8007E08C(void);
void func_8007E0AC(s32 bgm);
void func_8007E0CC(void);
void func_8007E0EC(void);
s8 Character_GetCharacterFromSlot(s32 characterSlot);
s32 Character_GetSlotFromCharacter(s32 character);
void func_8007E2B4(void);
void func_8007E398(void);

Gfx* func_8007E410(Gfx* gfx, TexturePtr texture, TexturePtr palette, s32 format, s32 unkTmemFlag, s32 left, s32 top, s32 width, s32 height, u16 unkDrawFlag);
void func_8007ECCC(u16* pixel, s32 textureSize);
s32 func_8007EFBC(u16* pixel, u16* paletteStart, s32 pixelCount);
Gfx* func_8007F090(Gfx* gfx, s32 arg1, s32 arg2, s32 arg3);

void func_8007F4E0(s32 venue, s32 skybox);

void LeoFault_LoadFonts(void);
void func_8007F9E0(void);
void LeoFault_DrawErrorNumber(s32);
void LeoFault_DrawReferUserGuide(void);
void LeoFault_DrawCautionDoNotRemove(void);
void LeoFault_DrawCautionDoNotRemovePleaseInsert(void);
void LeoFault_DrawReinsertDisk(void);
void LeoFault_DrawWrongDisk(void);
void LeoFault_DrawIsDiskInserted(void);
void LeoFault_DrawInsertInitialDiskUsed(void);

void Fault_SetFrameBuffer(FrameBuffer* buffer, u16 width, u16 height);
void Fault_Init(void);

Gfx* Camera_Draw(Gfx* gfx, s32 scissorBoxType, s32 cameraIndex);
void Camera_Init(void);
void Camera_Update(void);
void Camera_SendEndingCameraMessage(s32 msg);
f32 func_8008960C(f32 arg0);
void func_8008969C(void);
void func_80089724(void);
void func_80089BD0(void);
void func_8008AA8C(void);
void func_8008B1CC(void);
void Racer_Init(void);
void func_8008D7E8(void);
void func_8008D824(void);
void func_8008D8E8(void);
void func_80095144(void);
void Racer_Update(void);
Gfx* Racer_Draw(Gfx* gfx, s32 playerIndex);
Gfx* func_8009CBE8(Gfx* gfx, s32 arg1, s32 red, s32 green, s32 blue);
Gfx* func_8009CCBC(Gfx* gfx, s32 character, s32 arg2);
Gfx* func_8009CD60(Gfx* gfx, s32 character);
Gfx* func_8009CE70(Gfx* gfx, s32 character);
Gfx* func_8009CEA0(Gfx* gfx, s32 character);

void func_8009CED0(s32 venue);
s32 func_8009D16C(RacerSegmentPositionInfo* arg0, f32 arg1, f32 arg2, f32 arg3, Mtx3F* arg4);
s32 Course_SplineCalculateTensions(CourseInfo* courseInfo);
f32 Course_SplineGetLengthInfo(CourseSegment*, f32, f32*);
f32 Course_SplineGetTangent(CourseSegment*, f32, Vec3f*);
void Course_SplineGetPosition(CourseSegment*, f32, Vec3f*);
f32 Course_SplineGetBasis(CourseSegment*, f32, Mtx3F*, f32);
void Course_SegmentLengthsInit(CourseInfo* courseInfo);
f32 func_8009DFA0(RacerSegmentPositionInfo* arg0);
s32 Course_CalculateChecksum(void);

s32 func_800A2D2C(CourseInfo* arg0, Vtx* arg1);
void Course_GenerateRandomCourse(void);
void Course_Init(void);
void Course_Update(void);
Gfx* Course_DrawModel(Gfx* gfx, Vtx* vtx, s32 vtxCount);
Gfx* Course_Draw(Gfx* gfx, s32 playerIndex);

void mio0Decode(u8*, void*);
s32 func_800AA6BC(u8*);

void AudioThread_InitMesgQueues(void);
void Audio_Update(void);
void Audio_PreNMI(void);
void Audio_Init(void);
void Audio_SetOutMode(u8 soundMode);
void Audio_PlayerFinished(u8);
void Audio_SetEnemyEnginePan(u8);
void Audio_SetNearestEnemy(u8 racerId);
void Audio_PlayerLevelSEStart(u8, u8);
void Audio_PlayerLevelSEStop(u8, u8);
void Audio_PlayerTriggerSEStart(u8 racerId, u8 sfxId);
void Audio_TriggerSystemSE(u8 sfxId);
void Audio_Hanabi(u8 pan, u8 volume);
void Audio_PlayerEngineEchoStart(u8 playerIndex);
void Audio_PlayerEngineEchoStop(u8);
void Audio_PlayerEngineStop(u8);
void func_800BAE5C(u8 playerIndex);
void Audio_BetaBgmStart(u8);
void Audio_BetaBgmStop(void);
void Audio_RomBgmStart(u8);
void Audio_StartDemo(void);
void Audio_Retire(void);
void Audio_LevelSEFadeout(void);
void Audio_BetaBgmStop2(void);
void Audio_BetaBgmStop3(void);
void Audio_PauseSet(u8 status);
void Audio_SetPlayerMode(u8 numPlayersIndex);
void Audio_AllSoundStop(void);
void Audio_SESeqStart(void);
void Audio_ChangeSoundMode(s32);
void Audio_Chakuchi(u8, f32);
void Audio_GuitarSeqStart(void);

bool LeoDD_CheckPresence(void);

void Transition_HideSet(void);
void Transition_AppearSet(void);
void Transition_SetArgument(s32, s32);
s32 Transition_Update(void);
Gfx* Transition_Draw(Gfx*);
s32 Save_LoadGhost(s32);
s32 Save_UpdateCharacterSave(s32 courseIndex);
s32 Save_UpdateCupSave(u8* cupCompletion);
s32 Save_SaveCourseRecordProfiles(s32);
s32 Save_UpdateCourseCharacterSave(s32);
s32 Save_SaveSettingsProfiles(void);
s32 Save_LoadGhostInfo(GhostInfo*);
s32 func_i2_801017B8(s32 courseIndex);
s32 Save_InitGhost(s32 courseIndex);
OSPiHandle* Sram_Init(void);
void Sram_ReadWrite(s32 direction, u32 offset, void* dramAddr, size_t size);
s32 Save_LoadStaffGhostRecord(GhostInfo*, s32);
void func_i2_80103A70(void);
void Race_Init(void);
s32 Race_Update(void);
Gfx* Race_Draw(Gfx*);
void Effects_Init(void);
void Effects_Update(void);
s32 Effects_SpawnCollisionSparks(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, f32 scale, Racer* racer);
s32 Effects_SpawnExplosion1(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, f32 scale, Racer* racer);
s32 Effects_SpawnExplosion2(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, f32 scale, Racer* racer);
s32 Effects_SpawnFlyingSparks(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, Racer* racer);
s32 Effects_SpawnSmoke(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, f32 scale, Racer* racer);
s32 Effects_SpawnFallExplosion(f32 scale, Racer* racer);
s32 Effects_SpawnMachineDebris(f32 xPos, f32 yPos, f32 zPos, f32 xVelocity, f32 yVelocity, f32 zVelocity, Mtx3F* racerBasis, s32 red, s32 green, s32 blue, Racer* racer);
void Font_IntToString(s32 num, s8* str);
s32 Font_GetCharIndex(s8* str, s32 fontSetLowercase);
s32 Font_GetCharacterWidth(s8* str, s32 fontSet);
s32 Font_GetStringWidth(s8* str, s32 fontSet, s32 additionalSpacing);
Gfx* Font_DrawString(Gfx* gfx, s32 left, s32 top, s8* str, s32 additionalSpacing, s32 fontSet, s32 arg6);
Gfx* Font_DrawScaledString(Gfx* gfx, s32 left, s32 top, s8* str, s32 additionalSpacing, s32 fontSet, s32 arg6, f32 scaleX, f32 scaleY);
Gfx* Font_DrawMachineStatValue(Gfx* gfx, s32 left, s32 top, s32 statValue);
Gfx* Font_DrawMachineWeight(Gfx* gfx, s32 left, s32 top, u32 weight);
Gfx* Font_DrawMachineWeightSmall(Gfx* gfx, s32 left, s32 top, u32 weight);

f32 func_i3_fabsf(f32 num);
void func_i3_80116C4C(void);
void Cpu_InitRacer(Racer* racer);
void Menus_Update(void);
void Menus_Init(void);
Gfx* Menus_Player1SpecialDraw(Gfx* gfx, s32 playerIndex);
Gfx* Menus_Draw(Gfx* gfx);
void func_i3_8012F324(void);
Gfx* Hud_DrawTimerScisThousandths(Gfx* gfx, s32 time, s32 left, s32 top, f32 scale);
void Hud_InitRacePortraits(void);
void Hud_ResetLivesChangeCounter(void);
void Minimap_InitCourseMinimap(void);
void Background_Init(void);
void Background_Update(void);
Gfx* Background_Draw(Gfx* gfx, s32 cameraIndex, s32 scissorBoxType);
void RecordsEntry_Init(void);
bool RecordsEntry_Update(void);
Gfx* RecordsEntry_DrawRecords(Gfx*, s32);
Gfx* RecordsEntry_DrawSpeed(Gfx*, s32, s32, f32, bool, bool);
void RecordsEntry_SetDrawArrows(bool drawArrows);

void MachineSelect_Init(void);
void MachineSettings_Init(void);
s32 MachineSelect_Update(void);
s32 MachineSettings_Update(void);
Gfx* MachineSelect_Draw(Gfx*);
Gfx* MachineSettings_Draw(Gfx*);
void MachineSelect_HeaderInit(void);
void func_i4_80116E8C(Object*);
void MachineSettings_PortraitInit(Object*);
void MachineSelect_PortraitInit(Object*);
void MachineSelect_CursorNumInit(Object*);
void MachineSelect_CursorInit(void);
void MachineSelect_MachineInit(Object*);
void MachineSettings_MachineInit(Object*);
void MachineSettings_EngineWeightInit(void);
void MachineSettings_StatsInit(void);
void MachineSettings_NameCardInit(Object*);
void MachineSettings_SliderInit(void);
void MachineSelect_DifficultyCupsInit(Object*);
void MachineSelect_StatsInit(void);
void MachineSelect_OkInit(Object*);
void MachineSettings_OkInit(Object*);
Gfx* MachineSelect_BackgroundDraw(Gfx*);
Gfx* MachineSelect_HeaderDraw(Gfx*, Object*);
Gfx* func_i4_80117BE0(Gfx*, Object*);
Gfx* MachineSettings_PortraitDraw(Gfx*, Object*);
Gfx* MachineSelect_StatsDraw(Gfx*, Object*);
Gfx* MachineSelect_PortraitDraw(Gfx*, Object*);
Gfx* MachineSelect_CursorNumDraw(Gfx*, Object*);
Gfx* MachineSelect_CursorDraw(Gfx*, Object*);
Gfx* MachineSelect_MachineDraw(Gfx*, Object*);
Gfx* MachineSelect_OkDraw(Gfx*, Object*);
Gfx* MachineSettings_NameDraw(Gfx*);
Gfx* MachineSettings_MachineDraw(Gfx*, Object*);
Gfx* MachineSettings_EngineWeightDraw(Gfx*, Object*);
Gfx* MachineSettings_StatsDraw(Gfx*, Object*);
Gfx* func_i4_801193B8(Gfx*, Object*);
Gfx* MachineSettings_NameCardDraw(Gfx*, Object*);
Gfx* MachineSettings_SliderDraw(Gfx*, Object*);
Gfx* MachineSettings_SplitscreenDraw(Gfx*);
Gfx* MachineSelect_DifficultyCupsDraw(Gfx*, Object*);
Gfx* MachineSelect_NameDraw(Gfx*, Object*);
Gfx* MachineSettings_OkDraw(Gfx*, Object*);
void func_i4_80119BB8(Object*);
void MachineSettings_PortraitUpdate(Object*);
void MachineSelect_PortraitUpdate(Object*);
void MachineSelect_CursorNumUpdate(Object*);
void MachineSelect_CursorUpdate(Object*);
void MachineSelect_MachineUpdate(Object*);
void MachineSettings_MachineUpdate(Object*);
void MachineSelect_OkUpdate(Object*);
void MachineSettings_OkUpdate(Object*);
void MachineSettings_NameCardUpdate(Object*);
void func_i4_8011A7B8(void);
void Title_Init(void);
s32 Title_Update(void);
Gfx* Title_Draw(Gfx*);
void Title_BackgroundInit(Object*);
void func_i4_8011B0C8(void);
void Title_LogoInit(Object*);
void func_i4_8011B134(void);
void Title_StartInit(Object*);
void func_i4_8011B1E4(void);
void Title_CopyrightInit(void);
void Title_DiskDriveInit(Object*);
void Title_BackgroundUpdate(Object*);
Gfx* Title_BackgroundDraw(Gfx*, Object*);
Gfx* func_i4_8011B3DC(Gfx*, Object*);
Gfx* Title_LogoDraw(Gfx*, Object*);
Gfx* func_i4_8011B438(Gfx*, Object*);
Gfx* Title_StartDraw(Gfx*, Object*);
Gfx* func_i4_8011B668(Gfx*, Object*);
Gfx* Title_CopyrightDraw(Gfx*, Object*);
Gfx* Title_DiskDriveDraw(Gfx*, Object*);
void Title_DiskDriveUpdate(Object*);

void CourseSelect_Init(void);
void NextCourseSelect_Init(void);
s32 CourseSelect_Update(void);
s32 NextCourseSelect_Update(void);
Gfx* CourseSelect_Draw(Gfx*);
void CourseSelect_BackgroundInit(Object*);
void CourseSelect_ModelInit(void);
void CourseSelect_CupInit(Object*);
void CourseSelect_HeaderInit(Object*);
void CourseSelect_OkInit(Object*);
void CourseSelect_ArrowsInit(Object*);
void CourseSelect_GhostMarkerInit(Object*);
void CourseSelect_GhostOptionInit(Object*);
Gfx* CourseSelect_BackgroundDraw(Gfx*, Object*);
Gfx* CourseSelect_ModelDraw(Gfx*, Object*);
Gfx* CourseSelect_CupDraw(Gfx*, Object*);
Gfx* CourseSelect_HeaderDraw(Gfx*, Object*);
Gfx* CourseSelect_OkDraw(Gfx*, Object*);
Gfx* CourseSelect_ArrowsDraw(Gfx*, Object*);
Gfx* CourseSelect_NameDraw(Gfx*);
Gfx* CourseSelect_GhostMarkerDraw(Gfx*, Object*);
Gfx* CourseSelect_GhostOptionDraw(Gfx*, Object*);
void CourseSelect_ModelUpdate(Object*);
void CourseSelect_CupUpdate(Object*);
void CourseSelect_OkUpdate(Object*);
void CourseSelect_ArrowsUpdate(Object*);
void CourseSelect_GhostMarkerUpdate(Object*);
void CourseSelect_GhostOptionUpdate(Object*);

void MainMenu_Init(void);
s32 MainMenu_Update(void);
Gfx* MainMenu_Draw(Gfx*);
void MainMenu_BackgroundInit(Object*);
void MainMenu_SignInit(Object*);
void MainMenu_HeaderInit(Object*);
void MainMenu_NumPlayersInit(void);
void MainMenu_DifficultyInit(void);
void MainMenu_TimeAttackModeInit(void);
void MainMenu_OkInit(Object*);
void MainMenu_UnlockEverythingInit(Object*);
Gfx* MainMenu_SignDraw(Gfx*, Object*);
Gfx* MainMenu_BackgroundDraw(Gfx*, Object*);
Gfx* MainMenu_HeaderDraw(Gfx*, Object*);
Gfx* MainMenu_NumPlayersDraw(Gfx*, Object*);
Gfx* MainMenu_DifficultyDraw(Gfx*, Object*);
Gfx* MainMenu_TimeAttackModeDraw(Gfx*, Object*);
Gfx* MainMenu_OkDraw(Gfx*, Object*);
void MainMenu_OkUpdate(Object*);
void MainMenu_UnlockEverythingUpdate(Object*);
void Credits_ObjectInit(s32 cmdId, s32 left, s32 top, s8 priority);
void Credits_Init(void);
s32 Credits_Update(void);
Gfx* Credits_Draw(Gfx*);
void func_i6_8011C404(void);
void func_i6_8011CBB4(void);
void func_i6_8011D394(void);
Gfx* func_i6_8011D8C8(Gfx* gfx);
void OptionsMenu_Init(void);
s32 OptionsMenu_Update(void);
Gfx* OptionsMenu_Draw(Gfx*);

void EndingCutscene_Init(void);
s32 EndingCutscene_Update(void);
Gfx* EndingCutscene_Draw(Gfx*);
Gfx* EndingCutscene_DrawScrollingResults(Gfx* gfx);
void EndingCutscene_InitPodiums(void);
Gfx* EndingCutscene_DrawPodiums(Gfx* gfx);
Gfx* EndingCutsceneEffects_DrawFireworks(Gfx* gfx);

void Records_Init(void);
s32 Records_Update(void);
Gfx* Records_Draw(Gfx*);

Gfx* Machine_DrawCustom(Gfx* gfx, s32 lod, s32 frontType, s32 rearType, s32 wingType, s32 decalR, s32 decalG, s32 decalB, s32 numberR, s32 numberG, s32 numberB, s32 cockpitPrimR, s32 cockpitPrimG, s32 cockpitPrimB, s32 cockpitEnvR, s32 cockpitEnvG, s32 cockpitEnvB);

Gfx* Machine_DrawSuperFalconLod1(Gfx* gfx);
Gfx* Machine_DrawSuperFalconLod2(Gfx* gfx);
Gfx* Machine_DrawSuperFalconLod3(Gfx* gfx);
Gfx* Machine_DrawSuperFalconLod4(Gfx* gfx);
Gfx* Machine_DrawSuperFalconLod5(Gfx* gfx);
Gfx* Machine_DrawSuperStingrayLod1(Gfx* gfx);
Gfx* Machine_DrawSuperStingrayLod2(Gfx* gfx);
Gfx* Machine_DrawSuperStingrayLod3(Gfx* gfx);
Gfx* Machine_DrawSuperStingrayLod4(Gfx* gfx);
Gfx* Machine_DrawSuperStingrayLod5(Gfx* gfx);
Gfx* Machine_DrawSuperCatLod1(Gfx* gfx);
Gfx* Machine_DrawSuperCatLod2(Gfx* gfx);
Gfx* Machine_DrawSuperCatLod3(Gfx* gfx);
Gfx* Machine_DrawSuperCatLod4(Gfx* gfx);
Gfx* Machine_DrawSuperCatLod5(Gfx* gfx);
Gfx* Machine_DrawBlueFalconLod1(Gfx* gfx);
Gfx* Machine_DrawBlueFalconLod2(Gfx* gfx);
Gfx* Machine_DrawBlueFalconLod3(Gfx* gfx);
Gfx* Machine_DrawBlueFalconLod4(Gfx* gfx);
Gfx* Machine_DrawBlueFalconLod5(Gfx* gfx);
Gfx* Machine_DrawGoldenFoxLod1(Gfx* gfx);
Gfx* Machine_DrawGoldenFoxLod2(Gfx* gfx);
Gfx* Machine_DrawGoldenFoxLod3(Gfx* gfx);
Gfx* Machine_DrawGoldenFoxLod4(Gfx* gfx);
Gfx* Machine_DrawGoldenFoxLod5(Gfx* gfx);
Gfx* Machine_DrawWildGooseLod1(Gfx* gfx);
Gfx* Machine_DrawWildGooseLod2(Gfx* gfx);
Gfx* Machine_DrawWildGooseLod3(Gfx* gfx);
Gfx* Machine_DrawWildGooseLod4(Gfx* gfx);
Gfx* Machine_DrawWildGooseLod5(Gfx* gfx);
Gfx* Machine_DrawFireStingrayLod1(Gfx* gfx);
Gfx* Machine_DrawFireStingrayLod2(Gfx* gfx);
Gfx* Machine_DrawFireStingrayLod3(Gfx* gfx);
Gfx* Machine_DrawFireStingrayLod4(Gfx* gfx);
Gfx* Machine_DrawFireStingrayLod5(Gfx* gfx);
Gfx* Machine_DrawWhiteCatLod1(Gfx* gfx);
Gfx* Machine_DrawWhiteCatLod2(Gfx* gfx);
Gfx* Machine_DrawWhiteCatLod3(Gfx* gfx);
Gfx* Machine_DrawWhiteCatLod4(Gfx* gfx);
Gfx* Machine_DrawWhiteCatLod5(Gfx* gfx);
Gfx* Machine_DrawRedGazelleLod1(Gfx* gfx);
Gfx* Machine_DrawRedGazelleLod2(Gfx* gfx);
Gfx* Machine_DrawRedGazelleLod3(Gfx* gfx);
Gfx* Machine_DrawRedGazelleLod4(Gfx* gfx);
Gfx* Machine_DrawRedGazelleLod5(Gfx* gfx);
Gfx* Machine_DrawWonderWaspLod1(Gfx* gfx);
Gfx* Machine_DrawWonderWaspLod2(Gfx* gfx);
Gfx* Machine_DrawWonderWaspLod3(Gfx* gfx);
Gfx* Machine_DrawWonderWaspLod4(Gfx* gfx);
Gfx* Machine_DrawWonderWaspLod5(Gfx* gfx);
Gfx* Machine_DrawIronTigerLod1(Gfx* gfx);
Gfx* Machine_DrawIronTigerLod2(Gfx* gfx);
Gfx* Machine_DrawIronTigerLod3(Gfx* gfx);
Gfx* Machine_DrawIronTigerLod4(Gfx* gfx);
Gfx* Machine_DrawIronTigerLod5(Gfx* gfx);
Gfx* Machine_DrawDeepClawLod1(Gfx* gfx);
Gfx* Machine_DrawDeepClawLod2(Gfx* gfx);
Gfx* Machine_DrawDeepClawLod3(Gfx* gfx);
Gfx* Machine_DrawDeepClawLod4(Gfx* gfx);
Gfx* Machine_DrawDeepClawLod5(Gfx* gfx);
Gfx* Machine_DrawTwinNorittaLod1(Gfx* gfx);
Gfx* Machine_DrawTwinNorittaLod2(Gfx* gfx);
Gfx* Machine_DrawTwinNorittaLod3(Gfx* gfx);
Gfx* Machine_DrawTwinNorittaLod4(Gfx* gfx);
Gfx* Machine_DrawTwinNorittaLod5(Gfx* gfx);
Gfx* Machine_DrawSuperPiranhaLod1(Gfx* gfx);
Gfx* Machine_DrawSuperPiranhaLod2(Gfx* gfx);
Gfx* Machine_DrawSuperPiranhaLod3(Gfx* gfx);
Gfx* Machine_DrawSuperPiranhaLod4(Gfx* gfx);
Gfx* Machine_DrawSuperPiranhaLod5(Gfx* gfx);
Gfx* Machine_DrawMightyHurricaneLod1(Gfx* gfx);
Gfx* Machine_DrawMightyHurricaneLod2(Gfx* gfx);
Gfx* Machine_DrawMightyHurricaneLod3(Gfx* gfx);
Gfx* Machine_DrawMightyHurricaneLod4(Gfx* gfx);
Gfx* Machine_DrawMightyHurricaneLod5(Gfx* gfx);
Gfx* Machine_DrawLittleWyvernLod1(Gfx* gfx);
Gfx* Machine_DrawLittleWyvernLod2(Gfx* gfx);
Gfx* Machine_DrawLittleWyvernLod3(Gfx* gfx);
Gfx* Machine_DrawLittleWyvernLod4(Gfx* gfx);
Gfx* Machine_DrawLittleWyvernLod5(Gfx* gfx);
Gfx* Machine_DrawSpaceAnglerLod1(Gfx* gfx);
Gfx* Machine_DrawSpaceAnglerLod2(Gfx* gfx);
Gfx* Machine_DrawSpaceAnglerLod3(Gfx* gfx);
Gfx* Machine_DrawSpaceAnglerLod4(Gfx* gfx);
Gfx* Machine_DrawSpaceAnglerLod5(Gfx* gfx);
Gfx* Machine_DrawGreenPantherLod1(Gfx* gfx);
Gfx* Machine_DrawGreenPantherLod2(Gfx* gfx);
Gfx* Machine_DrawGreenPantherLod3(Gfx* gfx);
Gfx* Machine_DrawGreenPantherLod4(Gfx* gfx);
Gfx* Machine_DrawGreenPantherLod5(Gfx* gfx);
Gfx* Machine_DrawBlackBullLod1(Gfx* gfx);
Gfx* Machine_DrawBlackBullLod2(Gfx* gfx);
Gfx* Machine_DrawBlackBullLod3(Gfx* gfx);
Gfx* Machine_DrawBlackBullLod4(Gfx* gfx);
Gfx* Machine_DrawBlackBullLod5(Gfx* gfx);
Gfx* Machine_DrawWildBoarLod1(Gfx* gfx);
Gfx* Machine_DrawWildBoarLod2(Gfx* gfx);
Gfx* Machine_DrawWildBoarLod3(Gfx* gfx);
Gfx* Machine_DrawWildBoarLod4(Gfx* gfx);
Gfx* Machine_DrawWildBoarLod5(Gfx* gfx);
Gfx* Machine_DrawAstroRobinLod1(Gfx* gfx);
Gfx* Machine_DrawAstroRobinLod2(Gfx* gfx);
Gfx* Machine_DrawAstroRobinLod3(Gfx* gfx);
Gfx* Machine_DrawAstroRobinLod4(Gfx* gfx);
Gfx* Machine_DrawAstroRobinLod5(Gfx* gfx);
Gfx* Machine_DrawKingMeteorLod1(Gfx* gfx);
Gfx* Machine_DrawKingMeteorLod2(Gfx* gfx);
Gfx* Machine_DrawKingMeteorLod3(Gfx* gfx);
Gfx* Machine_DrawKingMeteorLod4(Gfx* gfx);
Gfx* Machine_DrawKingMeteorLod5(Gfx* gfx);
Gfx* Machine_DrawQueenMeteorLod1(Gfx* gfx);
Gfx* Machine_DrawQueenMeteorLod2(Gfx* gfx);
Gfx* Machine_DrawQueenMeteorLod3(Gfx* gfx);
Gfx* Machine_DrawQueenMeteorLod4(Gfx* gfx);
Gfx* Machine_DrawQueenMeteorLod5(Gfx* gfx);
Gfx* Machine_DrawGreatStarLod1(Gfx* gfx);
Gfx* Machine_DrawGreatStarLod2(Gfx* gfx);
Gfx* Machine_DrawGreatStarLod3(Gfx* gfx);
Gfx* Machine_DrawGreatStarLod4(Gfx* gfx);
Gfx* Machine_DrawGreatStarLod5(Gfx* gfx);
Gfx* Machine_DrawHyperSpeederLod1(Gfx* gfx);
Gfx* Machine_DrawHyperSpeederLod2(Gfx* gfx);
Gfx* Machine_DrawHyperSpeederLod3(Gfx* gfx);
Gfx* Machine_DrawHyperSpeederLod4(Gfx* gfx);
Gfx* Machine_DrawHyperSpeederLod5(Gfx* gfx);
Gfx* Machine_DrawDeathAnchorLod1(Gfx* gfx);
Gfx* Machine_DrawDeathAnchorLod2(Gfx* gfx);
Gfx* Machine_DrawDeathAnchorLod3(Gfx* gfx);
Gfx* Machine_DrawDeathAnchorLod4(Gfx* gfx);
Gfx* Machine_DrawDeathAnchorLod5(Gfx* gfx);
Gfx* Machine_DrawCrazyBearLod1(Gfx* gfx);
Gfx* Machine_DrawCrazyBearLod2(Gfx* gfx);
Gfx* Machine_DrawCrazyBearLod3(Gfx* gfx);
Gfx* Machine_DrawCrazyBearLod4(Gfx* gfx);
Gfx* Machine_DrawCrazyBearLod5(Gfx* gfx);
Gfx* Machine_DrawNightThunderLod1(Gfx* gfx);
Gfx* Machine_DrawNightThunderLod2(Gfx* gfx);
Gfx* Machine_DrawNightThunderLod3(Gfx* gfx);
Gfx* Machine_DrawNightThunderLod4(Gfx* gfx);
Gfx* Machine_DrawNightThunderLod5(Gfx* gfx);
Gfx* Machine_DrawBigFangLod1(Gfx* gfx);
Gfx* Machine_DrawBigFangLod2(Gfx* gfx);
Gfx* Machine_DrawBigFangLod3(Gfx* gfx);
Gfx* Machine_DrawBigFangLod4(Gfx* gfx);
Gfx* Machine_DrawBigFangLod5(Gfx* gfx);
Gfx* Machine_DrawMightyTyphoonLod1(Gfx* gfx);
Gfx* Machine_DrawMightyTyphoonLod2(Gfx* gfx);
Gfx* Machine_DrawMightyTyphoonLod3(Gfx* gfx);
Gfx* Machine_DrawMightyTyphoonLod4(Gfx* gfx);
Gfx* Machine_DrawMightyTyphoonLod5(Gfx* gfx);
Gfx* Machine_DrawMadWolfLod1(Gfx* gfx);
Gfx* Machine_DrawMadWolfLod2(Gfx* gfx);
Gfx* Machine_DrawMadWolfLod3(Gfx* gfx);
Gfx* Machine_DrawMadWolfLod4(Gfx* gfx);
Gfx* Machine_DrawMadWolfLod5(Gfx* gfx);
Gfx* Machine_DrawSonicPhantomLod1(Gfx* gfx);
Gfx* Machine_DrawSonicPhantomLod2(Gfx* gfx);
Gfx* Machine_DrawSonicPhantomLod3(Gfx* gfx);
Gfx* Machine_DrawSonicPhantomLod4(Gfx* gfx);
Gfx* Machine_DrawSonicPhantomLod5(Gfx* gfx);
Gfx* Machine_DrawBloodHawkLod1(Gfx* gfx);
Gfx* Machine_DrawBloodHawkLod2(Gfx* gfx);
Gfx* Machine_DrawBloodHawkLod3(Gfx* gfx);
Gfx* Machine_DrawBloodHawkLod4(Gfx* gfx);
Gfx* Machine_DrawBloodHawkLod5(Gfx* gfx);

Gfx* Machine_DrawLoadCustomTextures(Gfx* gfx, s32 logo, s32 number, s32 decal);

Gfx* Machine_DrawLoadBloodHawkTextures(Gfx* gfx);
Gfx* Machine_DrawLoadSonicPhantomTextures(Gfx* gfx);
Gfx* Machine_DrawLoadMadWolfTextures(Gfx* gfx);
Gfx* Machine_DrawLoadMightyTyphoonTextures(Gfx* gfx);
Gfx* Machine_DrawLoadBigFangTextures(Gfx* gfx);
Gfx* Machine_DrawLoadNightThunderTextures(Gfx* gfx);
Gfx* Machine_DrawLoadCrazyBearTextures(Gfx* gfx);
Gfx* Machine_DrawLoadDeathAnchorTextures(Gfx* gfx);
Gfx* Machine_DrawLoadHyperSpeederTextures(Gfx* gfx);
Gfx* Machine_DrawLoadGreatStarTextures(Gfx* gfx);
Gfx* Machine_DrawLoadQueenMeteorTextures(Gfx* gfx);
Gfx* Machine_DrawLoadKingMeteorTextures(Gfx* gfx);
Gfx* Machine_DrawLoadAstroRobinTextures(Gfx* gfx);
Gfx* Machine_DrawLoadWildBoarTextures(Gfx* gfx);
Gfx* Machine_DrawLoadBlackBullTextures(Gfx* gfx);
Gfx* Machine_DrawLoadGreenPantherTextures(Gfx* gfx);
Gfx* Machine_DrawLoadSpaceAnglerTextures(Gfx* gfx);
Gfx* Machine_DrawLoadLittleWyvernTextures(Gfx* gfx);
Gfx* Machine_DrawLoadMightyHurricaneTextures(Gfx* gfx);
Gfx* Machine_DrawLoadSuperPiranhaTextures(Gfx* gfx);
Gfx* Machine_DrawLoadTwinNorittaTextures(Gfx* gfx);
Gfx* Machine_DrawLoadDeepClawTextures(Gfx* gfx);
Gfx* Machine_DrawLoadIronTigerTextures(Gfx* gfx);
Gfx* Machine_DrawLoadWonderWaspTextures(Gfx* gfx);
Gfx* Machine_DrawLoadRedGazelleTextures(Gfx* gfx);
Gfx* Machine_DrawLoadWhiteCatTextures(Gfx* gfx);
Gfx* Machine_DrawLoadFireStingrayTextures(Gfx* gfx);
Gfx* Machine_DrawLoadWildGooseTextures(Gfx* gfx);
Gfx* Machine_DrawLoadGoldenFoxTextures(Gfx* gfx);
Gfx* Machine_DrawLoadBlueFalconTextures(Gfx* gfx);

s32 func_i10_80115DF0(void);

void func_i11_800FC730(void);

#endif // FUNCTIONS_H
