#ifndef FZX_GAME_H
#define FZX_GAME_H

typedef enum GameMode {
    /*  0x0 */ GAMEMODE_TITLE,
    /*  0x1 */ GAMEMODE_GP_RACE,
    /*  0x2 */ GAMEMODE_PRACTICE,
    /*  0x3 */ GAMEMODE_VS_2P,
    /*  0x4 */ GAMEMODE_VS_3P,
    /*  0x5 */ GAMEMODE_VS_4P,
    /*  0x6 */ GAMEMODE_RECORDS,
    /*  0x7 */ GAMEMODE_MAIN_MENU,
    /*  0x8 */ GAMEMODE_MACHINE_SELECT,
    /*  0x9 */ GAMEMODE_MACHINE_SETTINGS,
    /*  0xA */ GAMEMODE_COURSE_SELECT,
    /*  0xB */ GAMEMODE_SKIPPABLE_CREDITS,
    /*  0xC */ GAMEMODE_UNSKIPPABLE_CREDITS,
    /*  0xD */ GAMEMODE_COURSE_EDIT,
    /*  0xE */ GAMEMODE_TIME_ATTACK,
    /*  0xF */ GAMEMODE_GP_RACE_NEXT_COURSE,
    /* 0x10 */ GAMEMODE_CREATE_MACHINE,
    /* 0x11 */ GAMEMODE_GP_END_CS,
    /* 0x12 */ GAMEMODE_GP_RACE_NEXT_MACHINE_SETTINGS,
    /* 0x13 */ GAMEMODE_RECORDS_COURSE_SELECT,
    /* 0x14 */ GAMEMODE_OPTIONS_MENU,
    /* 0x15 */ GAMEMODE_DEATH_RACE,
} GameMode;

#define GET_MODE(gamemode) (gamemode & 0x1F)

#define GAMEMODE_F3D_MASK 0xC000

#define GFXMODE_F3DEX 0x0
#define GFXMODE_F3DLX 0x4000
#define GFXMODE_F3DFLX 0x8000

#define GAMEMODE_F3DLX(mode) ((mode) | GFXMODE_F3DLX)
#define GAMEMODE_F3DFLX(mode) ((mode) | GFXMODE_F3DFLX)

#define GAMEMODE_FLX_TITLE GAMEMODE_F3DFLX(GAMEMODE_TITLE)
#define GAMEMODE_FLX_MAIN_MENU GAMEMODE_F3DFLX(GAMEMODE_MAIN_MENU)
#define GAMEMODE_FLX_MACHINE_SELECT GAMEMODE_F3DFLX(GAMEMODE_MACHINE_SELECT)
#define GAMEMODE_LX_MACHINE_SETTINGS GAMEMODE_F3DLX(GAMEMODE_MACHINE_SETTINGS)
#define GAMEMODE_FLX_COURSE_SELECT GAMEMODE_F3DFLX(GAMEMODE_COURSE_SELECT)
#define GAMEMODE_FLX_SKIPPABLE_CREDITS GAMEMODE_F3DFLX(GAMEMODE_SKIPPABLE_CREDITS)
#define GAMEMODE_FLX_UNSKIPPABLE_CREDITS GAMEMODE_F3DFLX(GAMEMODE_UNSKIPPABLE_CREDITS)
#define GAMEMODE_FLX_GP_RACE_NEXT_COURSE GAMEMODE_F3DFLX(GAMEMODE_GP_RACE_NEXT_COURSE)
#define GAMEMODE_LX_GP_RACE_NEXT_MACHINE_SETTINGS GAMEMODE_F3DLX(GAMEMODE_GP_RACE_NEXT_MACHINE_SETTINGS)
#define GAMEMODE_FLX_RECORDS_COURSE_SELECT GAMEMODE_F3DFLX(GAMEMODE_RECORDS_COURSE_SELECT)
#define GAMEMODE_FLX_OPTIONS_MENU GAMEMODE_F3DFLX(GAMEMODE_OPTIONS_MENU)

typedef enum ModeSelect {
    /* 0 */ MODE_GP_RACE,
    /* 1 */ MODE_TIME_ATTACK,
    /* 2 */ MODE_DEATH_RACE,
    /* 3 */ MODE_VS_BATTLE,
    /* 4 */ MODE_COURSE_EDIT,
    /* 5 */ MODE_PRACTICE,
    /* 6 */ MODE_OPTIONS,
    /* 7 */ MODE_CREATE_MACHINE,
} ModeSelect;

typedef enum Difficulty {
    /* 0 */ NOVICE,
    /* 1 */ STANDARD,
    /* 2 */ EXPERT,
    /* 3 */ MASTER,
} Difficulty;

typedef enum Character {
    /* 00 */ CAPTAIN_FALCON,
    /* 01 */ DR_STEWART,
    /* 02 */ PICO,
    /* 03 */ SAMURAI_GOROH,
    /* 04 */ JODY_SUMMER,
    /* 05 */ MIGHTY_GAZELLE,
    /* 06 */ MR_EAD,
    /* 07 */ BABA,
    /* 08 */ OCTOMAN,
    /* 09 */ GOMAR_AND_SHIOH,
    /* 10 */ KATE_ALEN,
    /* 11 */ ROGER_BUSTER,
    /* 12 */ JAMES_MCCLOUD,
    /* 13 */ LEON,
    /* 14 */ ANTONIO_GUSTER,
    /* 15 */ BLACK_SHADOW,
    /* 16 */ MICHAEL_CHAIN,
    /* 17 */ JACK_LEVIN,
    /* 18 */ SUPER_ARROW,
    /* 19 */ MRS_ARROW,
    /* 20 */ JOHN_TANAKA,
    /* 21 */ BEASTMAN,
    /* 22 */ ZODA,
    /* 23 */ DR_CLASH,
    /* 24 */ SILVER_NEELSEN,
    /* 25 */ BIO_REX,
    /* 26 */ DRAQ,
    /* 27 */ BILLY,
    /* 28 */ THE_SKULL,
    /* 29 */ BLOOD_FALCON,
} Character;

typedef enum Cup {
    JACK_CUP,
    QUEEN_CUP,
    KING_CUP,
    JOKER_CUP,
    X_CUP,
    EDIT_CUP,
} Cup;

#endif // FZX_GAME_H
