#ifndef FZX_OBJECT_H
#define FZX_OBJECT_H

// Default to Most Common Names, Macros should always be used for variable fields
typedef struct Object {
    s32 cmdId;
    s32 state;
    s32 state2;
    s32 left;
    s32 top;
    s8 priority; // maybe depth is better
    s8 shouldDraw;
    union {
        s32 cacheIndex;
        u8* buffer;
    };
    union {
        s32 counter;
        Vp* vp;
    };
    s32 counter2;
    s8 unk_24[0x4];
} Object; // size = 0x28

// General Object Usage Macros

#define OBJECT_STATE(obj) ((obj)->state)
#define OBJECT_STATE2(obj) ((obj)->state2)
#define OBJECT_LEFT(obj) ((obj)->left)
#define OBJECT_TOP(obj) ((obj)->top)
#define OBJECT_CACHE_INDEX(obj) ((obj)->cacheIndex)
#define OBJECT_COUNTER(obj) ((obj)->counter)
#define OBJECT_COUNTER2(obj) ((obj)->counter2)

// Specific Object Macros

#define OBJECT_BUFFER(obj) ((obj)->buffer)

// Machine Select/Settings
#define MACHINE_VIEWPORT(machineObj) ((machineObj)->vp)
#define MACHINE_MINI_STATE(machineObj) ((machineObj)->counter2)
#define PORTRAIT_CHARACTER(portraitObj) ((portraitObj)->state)
#define NAME_CARD_CHARACTER(nameCardObj) ((nameCardObj)->state)

// Credits
#define INTRO_TIMER(obj) ((introObj)->cacheIndex)
#define MACHINE_INDEX(machineObj) ((machineObj)->counter2)
#define PORTRAIT_MACHINE_INDEX(portraitObj) ((portraitObj)->counter2)
#define MENU_LADY_DITHER_SCALE(menuLadyObj) ((menuLadyObj)->state2)

// Course Select
#define LEFT_ARROW_LEFT(arrowsObj) ((arrowsObj)->left)
#define RIGHT_ARROW_LEFT(arrowsObj) ((arrowsObj)->top)
#define LEFT_ARROW_ROTATION_CHANGE(arrowsObj) ((arrowsObj)->state)
#define RIGHT_ARROW_ROTATION_CHANGE(arrowsObj) ((arrowsObj)->state2)
#define LEFT_ARROW_ROTATION(arrowsObj) ((arrowsObj)->counter)
#define RIGHT_ARROW_ROTATION(arrowsObj) ((arrowsObj)->counter2)
#define GHOST_MARKER_COURSE(ghostMarkerObj) ((ghostMarkerObj)->state)
#define GHOST_MARKER_OFFSET(ghostMarkerObj) ((ghostMarkerObj)->counter)
#define UNLOCK_EVERYTHING_ROMDATA(unlockEverythingObj) ((unlockEverythingObj)->counter)

typedef enum ObjectIds {
    OBJECT_FREE,
    OBJECT_FRAMEBUFFER = 5,
    OBJECT_TITLE_BACKGROUND = 10,
    OBJECT_12 = 12,
    OBJECT_13,
    OBJECT_14,
    OBJECT_TITLE_LOGO,
    OBJECT_16,
    OBJECT_TITLE_PUSH_START,
    OBJECT_18,
    OBJECT_TITLE_COPYRIGHT,
    OBJECT_TITLE_DISK_DRIVE,
    OBJECT_MACHINE_SELECT_BACKGROUND = 30,
    OBJECT_MACHINE_SELECT_HEADER,
    OBJECT_32,
    OBJECT_MACHINE_SELECT_PORTRAIT_0,
    OBJECT_MACHINE_SELECT_PORTRAIT_1,
    OBJECT_MACHINE_SELECT_PORTRAIT_2,
    OBJECT_MACHINE_SELECT_PORTRAIT_3,
    OBJECT_MACHINE_SELECT_CURSOR_NUM_0 = 40,
    OBJECT_MACHINE_SELECT_CURSOR_NUM_1,
    OBJECT_MACHINE_SELECT_CURSOR_NUM_2,
    OBJECT_MACHINE_SELECT_CURSOR_NUM_3,
    OBJECT_MACHINE_SELECT_CURSOR,
    OBJECT_MACHINE_SELECT_MACHINE,
    OBJECT_MACHINE_SELECT_OK,
    OBJECT_MACHINE_SELECT_DIFFICULTY_CUPS,
    OBJECT_MACHINE_SELECT_NAME,
    OBJECT_MACHINE_SETTINGS_NAME = 50,
    OBJECT_MACHINE_SETTINGS_ENGINE_WEIGHT,
    OBJECT_MACHINE_SETTINGS_STATS,
    OBJECT_MACHINE_SETTINGS_MACHINE,
    OBJECT_MACHINE_SETTINGS_NAME_CARD,
    OBJECT_MACHINE_SETTINGS_SLIDER,
    OBJECT_MACHINE_SETTINGS_SPLITSCREEN_BARS,
    OBJECT_MACHINE_SETTINGS_OK,
    OBJECT_58,
    OBJECT_MACHINE_SETTINGS_BACKGROUND,
    OBJECT_MACHINE_SETTINGS_PORTRAIT_0,
    OBJECT_MACHINE_SETTINGS_PORTRAIT_1,
    OBJECT_MACHINE_SETTINGS_PORTRAIT_2,
    OBJECT_MACHINE_SETTINGS_PORTRAIT_3,
    OBJECT_MACHINE_SELECT_STATS_0 = 65,
    OBJECT_MACHINE_SELECT_STATS_1,
    OBJECT_MACHINE_SELECT_STATS_2,
    OBJECT_MACHINE_SELECT_STATS_3,
    OBJECT_MAIN_MENU_BACKGROUND = 80,
    OBJECT_MAIN_MENU_MODE_SIGN_0,
    OBJECT_MAIN_MENU_MODE_SIGN_1,
    OBJECT_MAIN_MENU_MODE_SIGN_2,
    OBJECT_MAIN_MENU_MODE_SIGN_3,
    OBJECT_MAIN_MENU_MODE_SIGN_4,
    OBJECT_MAIN_MENU_MODE_SIGN_5,
    OBJECT_MAIN_MENU_MODE_SIGN_6,
    OBJECT_MAIN_MENU_MODE_SIGN_7,
    OBJECT_MAIN_MENU_HEADER,
    OBJECT_MAIN_MENU_SELECT_NUM_PLAYERS,
    OBJECT_MAIN_MENU_SELECT_DIFFICULTY = 92,
    OBJECT_MAIN_MENU_OK,
    OBJECT_MAIN_MENU_UNLOCK_EVERYTHING,
    OBJECT_MAIN_MENU_SELECT_TIME_ATTACK_MODE,
    OBJECT_100 = 100,
    OBJECT_COURSE_SELECT_BACKGROUND = 120,
    OBJECT_COURSE_SELECT_MODEL,
    OBJECT_COURSE_SELECT_CUP_0,
    OBJECT_COURSE_SELECT_CUP_1,
    OBJECT_COURSE_SELECT_CUP_2,
    OBJECT_COURSE_SELECT_CUP_3,
    OBJECT_COURSE_SELECT_CUP_4,
    OBJECT_COURSE_SELECT_CUP_5,
    OBJECT_COURSE_SELECT_OK,
    OBJECT_COURSE_SELECT_ARROWS,
    OBJECT_COURSE_SELECT_NAME,
    OBJECT_COURSE_SELECT_HEADER,
    OBJECT_COURSE_SELECT_GHOST_MARKER,
    OBJECT_COURSE_SELECT_GHOST_OPTION,
    OBJECT_140 = 140,
    OBJECT_150 = 150,
    OBJECT_CREDITS_MACHINES_OLD = 153,
    OBJECT_CREDITS_SCRIPT = 190,
    OBJECT_CREDITS_BACKGROUND,
    OBJECT_CREDITS_MACHINES,
    OBJECT_CREDITS_MENU_LADY,
    OBJECT_CREDITS_SEE_YOU_AGAIN,
    OBJECT_CREDITS_INTRO,
    OBJECT_CREDITS_COPYRIGHT,
    OBJECT_CREDITS_PORTRAITS,
    OBJECT_CREDITS_ROLE_0,
    OBJECT_CREDITS_ROLE_1,
    OBJECT_CREDITS_ROLE_2,
    OBJECT_CREDITS_ROLE_3,
    OBJECT_CREDITS_ROLE_4,
    OBJECT_CREDITS_ROLE_5,
    OBJECT_CREDITS_ROLE_6,
    OBJECT_CREDITS_ROLE_7,
    OBJECT_CREDITS_ROLE_8,
    OBJECT_CREDITS_ROLE_9,
    OBJECT_CREDITS_ROLE_10,
    OBJECT_CREDITS_ROLE_11,
    OBJECT_CREDITS_ROLE_12,
    OBJECT_CREDITS_ROLE_13,
    OBJECT_CREDITS_ROLE_14,
    OBJECT_CREDITS_ROLE_15,
    OBJECT_CREDITS_ROLE_16,
    OBJECT_CREDITS_ROLE_17,
    OBJECT_CREDITS_ROLE_18,
    OBJECT_CREDITS_ROLE_19,
    OBJECT_CREDITS_ROLE_20,
    OBJECT_CREDITS_ROLE_21,
    OBJECT_CREDITS_ROLE_22,
    OBJECT_CREDITS_ROLE_23,
    OBJECT_CREDITS_ROLE_24,
    OBJECT_CREDITS_ROLE_25,
    OBJECT_CREDITS_ROLE_26,
    OBJECT_CREDITS_ROLE_27,
    OBJECT_CREDITS_ROLE_28,
    OBJECT_CREDITS_ROLE_29,
    OBJECT_CREDITS_ROLE_30,
    OBJECT_CREDITS_NAME_0 = 230,
    OBJECT_CREDITS_NAME_1,
    OBJECT_CREDITS_NAME_2,
    OBJECT_CREDITS_NAME_3,
    OBJECT_CREDITS_NAME_4,
    OBJECT_CREDITS_NAME_5,
    OBJECT_CREDITS_NAME_6,
    OBJECT_CREDITS_NAME_7,
    OBJECT_CREDITS_NAME_8,
    OBJECT_CREDITS_NAME_9,
    OBJECT_CREDITS_NAME_10,
    OBJECT_CREDITS_NAME_11,
    OBJECT_CREDITS_NAME_12,
    OBJECT_CREDITS_NAME_13,
    OBJECT_CREDITS_NAME_14,
    OBJECT_CREDITS_NAME_15,
    OBJECT_CREDITS_NAME_16,
    OBJECT_CREDITS_NAME_17,
    OBJECT_CREDITS_NAME_18,
    OBJECT_CREDITS_NAME_19,
    OBJECT_CREDITS_NAME_20,
    OBJECT_CREDITS_NAME_21,
    OBJECT_CREDITS_NAME_22,
    OBJECT_CREDITS_NAME_23,
    OBJECT_CREDITS_NAME_24,
    OBJECT_CREDITS_NAME_25,
    OBJECT_CREDITS_NAME_26,
    OBJECT_CREDITS_NAME_27,
    OBJECT_CREDITS_NAME_28,
    OBJECT_CREDITS_NAME_29,
    OBJECT_CREDITS_NAME_30,
    OBJECT_CREDITS_NAME_31,
    OBJECT_CREDITS_NAME_32,
    OBJECT_CREDITS_NAME_33,
    OBJECT_CREDITS_NAME_34,
    OBJECT_CREDITS_NAME_35,
} ObjectIds;

#endif // FZX_OBJECT_H
