#ifndef SFX_H
#define SFX_H

#include "libultra/ultra64.h"

typedef enum SfxId {
    /*  0 */ NA_SE_NONE,
    /*  1 */ NA_SE_HIT_LANDMINE,
    /*  2 */ NA_SE_2,
    /*  3 */ NA_SE_3,
    /*  4 */ NA_SE_4,
    /*  5 */ NA_SE_5,
    /*  6 */ NA_SE_6,
    /*  7 */ NA_SE_7,
    /*  8 */ NA_SE_8,
    /*  9 */ NA_SE_9,
    /* 10 */ NA_SE_10,
    /* 11 */ NA_SE_11,
    /* 12 */ NA_SE_12,
    /* 13 */ NA_SE_13,
    /* 14 */ NA_SE_14,
    /* 15 */ NA_SE_15,
    /* 16 */ NA_SE_16,
    /* 17 */ NA_SE_17,
    /* 18 */ NA_SE_18,
    /* 19 */ NA_SE_LOW_ENERGY_SLOW,
    /* 20 */ NA_SE_LOW_ENERGY_MEDIUM,
    /* 21 */ NA_SE_LOW_ENERGY_FAST,
    /* 22 */ NA_SE_22,
    /* 23 */ NA_SE_23,
    /* 24 */ NA_SE_24,
    /* 25 */ NA_SE_25,
    /* 26 */ NA_SE_26,
    /* 27 */ NA_SE_27,
    /* 28 */ NA_SE_28,
    /* 29 */ NA_SE_29,
    /* 30 */ NA_SE_30,
    /* 31 */ NA_SE_31,
    /* 32 */ NA_SE_32,
    /* 33 */ NA_SE_33,
    /* 34 */ NA_SE_34,
    /* 35 */ NA_SE_35,
    /* 36 */ NA_SE_36,
    /* 37 */ NA_SE_37,
    /* 38 */ NA_SE_38,
    /* 39 */ NA_SE_39,
    /* 40 */ NA_SE_40,
    /* 41 */ NA_SE_41,
    /* 42 */ NA_SE_42,
    /* 43 */ NA_SE_43,
    /* 44 */ NA_SE_44,
    /* 45 */ NA_SE_45,
    /* 46 */ NA_SE_46,
    /* 47 */ NA_SE_47,
    /* 48 */ NA_SE_48,
    /* 49 */ NA_SE_49,
    /* 50 */ NA_SE_50,
    /* 51 */ NA_SE_51,
    /* 52 */ NA_SE_52,
    /* 53 */ NA_SE_53,
    /* 54 */ NA_SE_54,
    /* 55 */ NA_SE_55,
    /* 56 */ NA_SE_56,
    /* 57 */ NA_SE_57,
    /* 58 */ NA_SE_58,
    /* 59 */ NA_SE_59,
    /* 60 */ NA_SE_60,
    /* 61 */ NA_SE_61,
    /* 62 */ NA_SE_62,
    /* 63 */ NA_SE_63,
    /* 64 */ NA_SE_64,
    /* 65 */ NA_SE_65,
    /* 66 */ NA_SE_66,
    /* 67 */ NA_SE_67,
    /* 68 */ NA_SE_68,
    /* 69 */ NA_SE_69,
    // /* 63 */ NA_SE_MAX,
} SfxId;

typedef enum LevelSfxId {
    /*  0 */ NA_LEVEL_SE_NONE,
    /*  1 */ NA_LEVEL_SE_1,
    /*  2 */ NA_LEVEL_SE_2,
    /*  3 */ NA_LEVEL_SE_3,
    /*  4 */ NA_LEVEL_SE_4,
    /*  5 */ NA_LEVEL_SE_5,
    /*  6 */ NA_LEVEL_SE_6,
    /*  7 */ NA_LEVEL_SE_7,
    /*  8 */ NA_LEVEL_SE_8,
    /*  9 */ NA_LEVEL_SE_9,
    /* 10 */ NA_LEVEL_SE_10,
    /* 11 */ NA_LEVEL_SE_11,
} LevelSfxId;

typedef enum BgmId {
    /*  0 */ BGM_MUTE_CITY,
    /*  1 */ BGM_SILENCE,
    /*  2 */ BGM_SAND_OCEAN,
    /*  3 */ BGM_PORT_TOWN,
    /*  4 */ BGM_BIG_BLUE,
    /*  5 */ BGM_DEVILS_FOREST,
    /*  6 */ BGM_RED_CANYON,
    /*  7 */ BGM_SECTOR,
    /*  8 */ BGM_WHITE_LAND,
    /*  9 */ BGM_RAINBOW_ROAD,
    /* 10 */ BGM_NEW_03,
    /* 11 */ BGM_NEW_02,
    /* 12 */ BGM_NEW_01,
#ifdef EXPANSION_KIT
    /* 13 */ BGM_NEW_04,
#endif
    /* 14 */ BGM_TITLE,
    /* 15 */ BGM_SELECT,
    /* 16 */ BGM_OPTION,
#ifdef EXPANSION_KIT
    /* 17 */ BGM_DEATHRACE,
    /* 18 */ BGM_COURSE_EDITOR,
    /* 19 */ BGM_MACHINE_EDITOR,
    /* 20 */ BGM_EAD_DEMO,
#endif
    /* 21 */ BGM_21,
    /* 22 */ BGM_22,
    /* 23 */ BGM_23,
    /* 24 */ BGM_24,
    /* 25 */ BGM_GAMEOVER,
    /* 26 */ BGM_END_CS,
    /* 27 */ BGM_CREDITS,
    /* 28 */ BGM_DEMO,
    /* 29 */ BGM_DEATHRACE2,
    /* 99 */ BGM_NONE = 99,
} BgmId;

typedef enum SeqId {
#ifndef EXPANSION_KIT
    /*  0 */ SEQ_SOUND_EFFECTS,
    /*  1 */ SEQ_GUITAR,
#else
    /*  0 */ SEQ_GUITAR,
    /*  1 */ SEQ_SOUND_EFFECTS,
    /*  2 */ SEQ_DDBGM_MUTE_CITY,
    /*  3 */ SEQ_DDBGM_SILENCE,
    /*  4 */ SEQ_DDBGM_SAND_OCEAN,
    /*  5 */ SEQ_DDBGM_PORT_TOWN,
    /*  6 */ SEQ_DDBGM_BIG_BLUE,
    /*  7 */ SEQ_DDBGM_DEVILS_FOREST,
    /*  8 */ SEQ_DDBGM_RED_CANYON,
    /*  9 */ SEQ_DDBGM_SECTOR,
    /* 10 */ SEQ_DDBGM_WHITE_LAND,
    /* 11 */ SEQ_DDBGM_RAINBOW_ROAD,
    /* 12 */ SEQ_DDBGM_NEW_03,
    /* 13 */ SEQ_DDBGM_NEW_02,
    /* 14 */ SEQ_DDBGM_NEW_01,
    /* 15 */ SEQ_DDBGM_NEW_04,
    /* 16 */ SEQ_DDBGM_TITLE,
    /* 17 */ SEQ_DDBGM_SELECT,
    /* 18 */ SEQ_DDBGM_OPTION,
    /* 19 */ SEQ_DDBGM_DEATHRACE,
    /* 20 */ SEQ_DDBGM_COURSE_EDITOR,
    /* 21 */ SEQ_DDBGM_MACHINE_EDITOR,
    /* 22 */ SEQ_DDBGM_EAD_DEMO,
#endif
    /* 23 */ SEQ_MAX,
} SeqId;

typedef enum FontId {
#ifndef EXPANSION_KIT
    /*  0 */ FONT_SOUND_EFFECTS,
    /*  1 */ FONT_GUITAR,
#else
    /*  0 */ FONT_GUITAR,
    /*  1 */ FONT_SOUND_EFFECTS,
    /*  2 */ FONT_DDBGM_MUTE_CITY,
    /*  3 */ FONT_DDBGM_SILENCE,
    /*  4 */ FONT_DDBGM_SAND_OCEAN,
    /*  5 */ FONT_DDBGM_PORT_TOWN,
    /*  6 */ FONT_DDBGM_BIG_BLUE,
    /*  7 */ FONT_DDBGM_DEVILS_FOREST,
    /*  8 */ FONT_DDBGM_RED_CANYON,
    /*  9 */ FONT_DDBGM_SECTOR,
    /* 10 */ FONT_DDBGM_WHITE_LAND,
    /* 11 */ FONT_DDBGM_RAINBOW_ROAD,
    /* 12 */ FONT_DDBGM_NEW_03,
    /* 13 */ FONT_DDBGM_NEW_02,
    /* 14 */ FONT_DDBGM_NEW_01,
    /* 15 */ FONT_DDBGM_NEW_04,
    /* 16 */ FONT_DDBGM_TITLE,
    /* 17 */ FONT_DDBGM_SELECT,
    /* 18 */ FONT_DDBGM_OPTION,
    /* 19 */ FONT_DDBGM_DEATHRACE,
    /* 20 */ FONT_DDBGM_COURSE_EDITOR,
    /* 21 */ FONT_DDBGM_MACHINE_EDITOR,
    /* 22 */ FONT_DDBGM_EAD_DEMO,
#endif
    /* 23 */ FONT_MAX,
} FontId;

typedef enum SampleBankId {
    /*  0 */ SAMPLE_SOUND_EFFECTS,
    /*  1 */ SAMPLE_BGM,
    /*  2 */ SAMPLE_GUITAR,
#ifdef EXPANSION_KIT
    /*  3 */ SAMPLE_DD_SOUND_EFFECTS,
    /*  4 */ SAMPLE_DDBGM_MUTE_CITY,
    /*  5 */ SAMPLE_DDBGM_SILENCE,
    /*  6 */ SAMPLE_DDBGM_SAND_OCEAN,
    /*  7 */ SAMPLE_DDBGM_PORT_TOWN,
    /*  8 */ SAMPLE_DDBGM_BIG_BLUE,
    /*  9 */ SAMPLE_DDBGM_DEVILS_FOREST,
    /* 10 */ SAMPLE_DDBGM_RED_CANYON,
    /* 11 */ SAMPLE_DDBGM_SECTOR,
    /* 12 */ SAMPLE_DDBGM_WHITE_LAND,
    /* 13 */ SAMPLE_DDBGM_RAINBOW_ROAD,
    /* 14 */ SAMPLE_DDBGM_NEW_03,
    /* 15 */ SAMPLE_DDBGM_NEW_02,
    /* 16 */ SAMPLE_DDBGM_NEW_01,
    /* 17 */ SAMPLE_DDBGM_NEW_04,
    /* 18 */ SAMPLE_DDBGM_TITLE,
    /* 19 */ SAMPLE_DDBGM_SELECT,
    /* 20 */ SAMPLE_DDBGM_OPTION,
    /* 21 */ SAMPLE_DDBGM_DEATHRACE,
    /* 22 */ SAMPLE_DDBGM_COURSE_EDITOR,
    /* 23 */ SAMPLE_DDBGM_MACHINE_EDITOR,
    /* 24 */ SAMPLE_DDBGM_EAD_DEMO,
#endif
    /* 25 */ SAMPLE_MAX,
} SampleBankId;

typedef enum AudioLoadState {
    /* 0x01 */ AUDIO_LOAD_BGM_READY = 0x1,
    /* 0x10 */ AUDIO_LOAD_GUITAR_WAVE = 0x10,
    /* 0x11 */ AUDIO_LOAD_SE_WAVE,
    /* 0x12 */ AUDIO_LOAD_FONT_DDBGM_MUTE_CITY,
    /* 0x13 */ AUDIO_LOAD_FONT_DDBGM_SILENCE,
    /* 0x14 */ AUDIO_LOAD_FONT_DDBGM_SAND_OCEAN,
    /* 0x15 */ AUDIO_LOAD_FONT_DDBGM_PORT_TOWN,
    /* 0x16 */ AUDIO_LOAD_FONT_DDBGM_BIG_BLUE,
    /* 0x17 */ AUDIO_LOAD_FONT_DDBGM_DEVILS_FOREST,
    /* 0x18 */ AUDIO_LOAD_FONT_DDBGM_RED_CANYON,
    /* 0x19 */ AUDIO_LOAD_FONT_DDBGM_SECTOR,
    /* 0x1A */ AUDIO_LOAD_FONT_DDBGM_WHITE_LAND,
    /* 0x1B */ AUDIO_LOAD_FONT_DDBGM_RAINBOW_ROAD,
    /* 0x1C */ AUDIO_LOAD_FONT_DDBGM_NEW_03,
    /* 0x1D */ AUDIO_LOAD_FONT_DDBGM_NEW_02,
    /* 0x1E */ AUDIO_LOAD_FONT_DDBGM_NEW_01,
    /* 0x1F */ AUDIO_LOAD_FONT_DDBGM_NEW_04,
    /* 0x20 */ AUDIO_LOAD_FONT_DDBGM_TITLE,
    /* 0x21 */ AUDIO_LOAD_FONT_DDBGM_SELECT,
    /* 0x22 */ AUDIO_LOAD_FONT_DDBGM_OPTION,
    /* 0x23 */ AUDIO_LOAD_FONT_DDBGM_DEATHRACE,
    /* 0x24 */ AUDIO_LOAD_FONT_DDBGM_COURSE_EDITOR,
    /* 0x25 */ AUDIO_LOAD_FONT_DDBGM_MACHINE_EDITOR,
    /* 0x26 */ AUDIO_LOAD_FONT_DDBGM_EAD_DEMO,
    /* 0x27 */ AUDIO_LOAD_SEQ_DDBGM_MUTE_CITY,
    /* 0x28 */ AUDIO_LOAD_SEQ_DDBGM_SILENCE,
    /* 0x29 */ AUDIO_LOAD_SEQ_DDBGM_SAND_OCEAN,
    /* 0x2A */ AUDIO_LOAD_SEQ_DDBGM_PORT_TOWN,
    /* 0x2B */ AUDIO_LOAD_SEQ_DDBGM_BIG_BLUE,
    /* 0x2C */ AUDIO_LOAD_SEQ_DDBGM_DEVILS_FOREST,
    /* 0x2D */ AUDIO_LOAD_SEQ_DDBGM_RED_CANYON,
    /* 0x2E */ AUDIO_LOAD_SEQ_DDBGM_SECTOR,
    /* 0x2F */ AUDIO_LOAD_SEQ_DDBGM_WHITE_LAND,
    /* 0x30 */ AUDIO_LOAD_SEQ_DDBGM_RAINBOW_ROAD,
    /* 0x31 */ AUDIO_LOAD_SEQ_DDBGM_NEW_01,
    /* 0x32 */ AUDIO_LOAD_SEQ_DDBGM_NEW_02,
    /* 0x33 */ AUDIO_LOAD_SEQ_DDBGM_NEW_03,
    /* 0x34 */ AUDIO_LOAD_SEQ_DDBGM_NEW_04,
    /* 0x35 */ AUDIO_LOAD_SEQ_DDBGM_TITLE,
    /* 0x36 */ AUDIO_LOAD_SEQ_DDBGM_SELECT,
    /* 0x37 */ AUDIO_LOAD_SEQ_DDBGM_OPTION,
    /* 0x38 */ AUDIO_LOAD_SEQ_DDBGM_DEATHRACE,
    /* 0x39 */ AUDIO_LOAD_SEQ_DDBGM_COURSE_EDITOR,
    /* 0x3A */ AUDIO_LOAD_SEQ_DDBGM_MACHINE_EDITOR,
    /* 0x3B */ AUDIO_LOAD_SEQ_DDBGM_EAD_DEMO,
    /* 0x3C */ AUDIO_LOAD_COMPLETE,
    /* 0x3F */ AUDIO_LOAD_BGM_READY_INTER = 0x3F,
} AudioLoadState;

typedef enum SequenceLoadState {
    /* 0 */ SEQ_LOAD_INACTIVE,
    /* 1 */ SEQ_LOAD_BANK,
    /* 2 */ SEQ_LOAD_WAVE,
    /* 3 */ SEQ_LOAD_DATA,
    /* 4 */ SEQ_LOAD_BGM_DATA,
} SequenceLoadState;

typedef enum AudioPauseState {
    /* 0 */ AUDIO_PAUSE_UNPAUSED,
    /* 1 */ AUDIO_PAUSE_PAUSED,
    /* 2 */ AUDIO_PAUSE_TRANSITION,
} AudioPauseState;

#define BANK_GUITAR_LOAD_COMPLETE 1
#define BANK_SE_LOAD_COMPLETE 2

#define NA_SE_PLAYER_MAX 63

#define LEVEL_SE_2P(sfxId) ((sfxId) + 10)
#define LEVEL_SE_MP(sfxId) ((sfxId) + 20)

#endif // SFX_H
