.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* do not insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text

.align 4

/* Generated by spimdisasm 1.26.0 */

/* Handwritten function */
glabel __LeoBootGame3 # 0
lui         $t0, %hi(D_80000000)
addiu       $t0, $t0, %lo(D_80000000)
addiu       $t1, $t0, 0x4000
addiu       $t1, $t1, -0x20
mtc0        $zero, TagLo /* handwritten instruction */
mtc0        $zero, TagHi /* handwritten instruction */
.L800BB958:
cache       0x08, 0x0($t0) /* handwritten instruction */
sltu        $at, $t0, $t1
bnez        $at, .L800BB958
 addiu      $t0, $t0, 0x20
lui         $t0, 0x8000
addiu       $t2, $zero, 0x2000
addu        $t1, $t0, $t2
addiu       $t1, $t1, -0x10
.L800BB978:
cache       0x01, 0x0($t0) /* handwritten instruction */
sltu        $at, $t0, $t1
bnez        $at, .L800BB978
 addiu      $t0, $t0, (0x80000010 & 0xFFFF)
jr          $a0
 nop
nop
nop
nop
nop
