name: ci-validate
on:
  workflow_call:
    secrets:
      FZEROX_PASSPHRASE: { required: true }
      FZEROX_DEPENDENCIES: { required: true }
      FZEROX_TOKEN: { required: true }
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha || github.ref }}
    - name: Fetch Secrets
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.FZEROX_DEPENDENCIES }}
        token: ${{ secrets.FZEROX_TOKEN }}
        path: fzerox-secret
    - name: Decrypt Secrets
      working-directory: fzerox-secret
      run: |
        ./decrypt_secret.sh
        mv baserom.jp.ndd ..
      env:
          SECRET_PASSPHRASE: ${{ secrets.FZEROX_PASSPHRASE }}
          SECRET_NAME: baserom.jp.ndd
    - name: Decrypt Secrets Base
      working-directory: fzerox-secret
      run: |
        ./decrypt_secret.sh
        mv baserom.jp.rev0.z64 ..
      env:
          SECRET_PASSPHRASE: ${{ secrets.FZEROX_PASSPHRASE }}
          SECRET_NAME: baserom.jp.rev0.z64
    - name: Install package requirements
      run: sudo apt-get install -y git make git build-essential binutils-mips-linux-gnu python3 python3-pip

    - name: Install Python dependencies
      run: python3 -m pip install -r ./tools/requirements-python.txt

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: build toolchain
      run: make -s -C tools

    - name: Create z64dd baserom
      run: make setup EXPANSION_KIT=1

    - name: Compile
      run: make init EXPANSION_KIT=1

    - name: Generate objdiff report
      run: python3 -m mapfile_parser objdiff_report report.json --version ek

    - name: Upload progress report artifact
      uses: actions/upload-artifact@v4
      with:
        name: ek_report
        path: report.json

    - name: Upload progress to Discord
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: python3 tools/upload_progress_ek.py --discord_url ${{ secrets.DISCORD_URL_EK }}