name: Build JP

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request_target]

jobs:
  build_repo:
    name: Build repo
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install package requirements
      run: sudo apt-get install -y git make git build-essential binutils-mips-linux-gnu python3 python3-pip

    - name: Install Python dependencies
      run: python3 -m pip install -r ./tools/requirements-python.txt

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: build toolchain
      run: make -s -C tools

    - name: Get extra dependencies
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.FZEROX_DEPENDENCIES }}
        token: ${{ secrets.FZEROX_TOKEN }}
        path: fzerox-secret

    - name: Get the dependency
      run: cp -r fzerox-secret/baserom.jp.rev0.z64 ./

    - name: Compile
      run: make init
